runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --log-level debug --workers 3 --timeout 480 app:app

runtime_config:
  python_version: 3

env_variables:
  CONFIG_BUCKET: "browser-extension-configuration"
  CONFIG_FILE: ".env"

# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 5
